server:
  port: 8081
  servlet-path: /clientb
security:
  oauth2:
    client:
      client-id: clientB
      client-secret: clientsecret2
      user-authorization-uri: http://127.0.0.1:9999/server/oauth/authorize
      access-token-uri: http://127.0.0.1:9999/server/oauth/token
    resource:
      jwt:
        key-uri: http://127.0.0.1:9999/server/oauth/token_key
logging:
  level:
    org.springframework: debug
