server:
  port: 8082
  servlet-path: /clientb
security:
  oauth2:
    client:
      clientId: clientB
      clientSecret: secretB
      access-token-uri: http://127.0.0.1:9999/server/oauth/token
      user-authorization-uri: http://127.0.0.1:9999/server/oauth/authorize
    resource:
      jwt:
        key-uri: http://127.0.0.1:9999/server/oauth/token_key
