server:
  port: 8081
  context-path: /clientb
security:
  oauth2:
    client:
      clientId: client2
      clientSecret: secret2
      access-token-uri: http://127.0.0.1:8082/auth_server/oauth/token
      user-authorization-uri: http://127.0.0.1:8082/auth_server/oauth/authorize
    resource:
      jwt:
        key-uri: http://127.0.0.1:8082/auth_server/oauth/token_key
