server:
  port: 8081
  servlet-path: /clientb
security:
  oauth2:
    client:
      clientId: clientb
      clientSecret: secretb
      access-token-uri: http://127.0.0.1:8082/server/oauth/token
      user-authorization-uri: http://127.0.0.1:8082/server/oauth/authorize
    resource:
      jwt:
        key-uri: http://127.0.0.1:8082/server/oauth/token_key
