server:
  port: 10000



#security:
#  oauth2:
#    client:
#      # 授权服务器配置的client id
#      client-id: testclient
#      # 授权服务器配置的client secret
#      client-secret: testclient
#      scope: test
#      # 获取access token接口
#      access-token-uri: ${auth-server}/oauth/token
#      #  获取Authorization Code接口
#      user-authorization-uri: ${auth-server}/oauth/authorize
#    resource:
#      # 验证token的接口
#      token-info-uri: ${auth-server}/oauth/check_token
#      # 一个可以获取认证授权的自定义接口，可以在授权服务器，也可以在其他服务器上
#      # user-info-uri: ${auth-server}/user
#      # 如果同时配置了token-info-uri 和 user-info-uri，这个现象设置使用哪个取验证授权
#      # prefer-token-info: true
#





