server:
  port: 8001
  servlet:
    path: /client1

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:10000/oauth/check_token
      prefer-token-info: true

    client:
      access-token-uri: http://localhost:10000/oauth/token
      user-authorization-uri: http://localhost:10000/oauth/authorize
      client-id: client1
      client-secret: secret1
      registered-redirect-uri: http://localhost:8001/index

