# 认证服务器地址
auth-server: http://127.0.0.1:9999/auth

server:
  port: 8002
  servlet:
    contextPath: /ui

security:
  oauth2:
    client:
      client-id: client2
      client-secret: 165236
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
    resource:
      user-info-uri: ${auth-server}/user
