server:
  port: 8001

# 认证服务器地址
auth-server: http://127.0.0.1:9999

security:
  oauth2:
    client:
      client-id: client1
      client-secret: 154654
      scope: all
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
    resource:
       user-info-uri: ${auth-server}/user/me
