server:
  port: 9999
  context-path: /server

security:
#  oauth2:
#    client:
#      clientId: wechat
#      clientSecret: wechat
#      accessTokenUri: http://localhost:8081/auth/oauth/token
#      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
#    resource:
#      userInfoUri: http://localhost:8081/auth/user
  user:
    password: admin
#spring:
#  thymeleaf:
#    cache: false
#  security:
#    user:
#      name: admin
#      password: admin

#security.oauth2.client.authorized-grant-types: authorization_code,refresh_token,password
#security.oauth2.client.scope: openid