# 认证服务器地址
auth-server: http://127.0.0.1:10000

server:
  port: 8002

security:
  oauth2:
    client:
      client-id: testClient
      client-secret: testClient
      scope: all
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
    resource:
      token-info-uri: ${auth-server}/oauth/check_token
